### ISSUE TITLE
Highlighting of effective address with size

### ISSUE THREAD

**Issue by flamewing** [georgjz/motorola-68k-assembly#14]
There are two cases here:

* Absolute addresses:
```
    move.l  (Address).w, d1
    move.l  (Address).l, d1
```

* Indexed addresses
```
    move.l  6(a0, d0.w), d1
    move.l  6(a0, d0.l), d1
```

In both of those, the effective address size specifier is not highlighted. Specifically, what I am asking for is that these get highlighted:

* the `.w` and `.l` in `(Address).w` or `(Address).l` in absolute addresses
* the `.w` and `.l` in `d0.w` or `d0.l` in indexed effective addresses

**Comment by georgjz** [comment]
This should work now, but the scopes/colors are different for registers and labels.
