### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by georgjz** [georgjz/motorola-68k-assembly#15]
This is a list of missing instructions for 68k and variants:
* ~~`absw`~~ that's a macro
* `bhs`
* `blo`
* `divu`
* `bchg`

**Comment by flamewing** [comment]
A few more I mentioned in the (essentially duplicate) issue #17:

* `shs`
* `slo`
* `dbhs`
* `dblo`

**Comment by flamewing** [comment]
For what is worth, the `hs` and `lo` in these instructions are non-standard but widely supported alternate spellings of `cc` and `cs` condition codes.
