### ISSUE TITLE
Things get highlighted inside strings

### ISSUE THREAD

**Issue by flamewing** [georgjz/motorola-68k-assembly#21]
For example, in this fragment:

```
    dc.b    "Unhandled trap #0,d0 was triggered"
```

`trap` and `d0` appear highlighted. This happens for all grammars. I noticed this in my [debugger](https://github.com/flamewing/genesis-debugger/blob/master/src/Debugger.asm). Size specifiers (`.b`, `.w`, `.l`, `.s`) are also highlighted inside strings.

**Comment by georgjz** [comment]
I had that one before; it's because I moved the code for registers into a common file as to inject them into all grammars (instead of having duplicate code in all grammars). Seems like I'll have to roll that back.

**Comment by georgjz** [comment]
Should work again now. Gonna give the Z80 injection a shot next.
