### ISSUE TITLE
Missing highlighting on a few instructions

### ISSUE THREAD

**Issue by flamewing** [georgjz/motorola-68k-assembly#26]
I created a [large file](https://gist.github.com/flamewing/73973a94eaf3d24197db5e1080c6a56e) for AS with the intent of testing the 68k cycle byte counter extension you mentioned in issue #25, and I came across  a few instructions that are missing highlighting:

These are missing highlighting on the `.l`:
```68k
bchg.l	d0,d0
bchg.l	#i5,d0
```
(the other bit instructions highlight it correctly)

The following are not highlighted at all:

```68k
shs.b	<ea>	; Alias for scc.b	<ea>
slo.b	<ea>	; Alias for scs.b	<ea>
sbcd.b	d0,d0
sbcd.b	-(a0),-(a0)
divs.w	<ea>,d0
```

Here, `<ea>` stands for any addressing mode supported by the instructions (which can be seen in the file above).

All other instructions are highlighted, including `abcd` and `divu`.

**Comment by georgjz** [comment]
I have tested it against your example file, it should highlight those missing mnemonics now.

Thank you for pointing this out!
