### ISSUE TITLE
Support for AS

### ISSUE THREAD

**Issue by flamewing** [georgjz/motorola-68k-assembly#8]
I would like to suggest adding support for [AS](http://john.ccac.rwth-aachen.de:8000/as/). If it helps, there is a [z80 extension](https://github.com/mborik/z80-macroasm-vscode) which supports it, and could be used to speed up writing the grammar and adding z80 support for z80 injection.

From what I understand, it might also be possible to make your extension depend on that extension, and delegate to it in z80 portions, which would make things even simpler. I know that some c++ extensions do that, but I am not well versed in extension development.

**Comment by georgjz** [comment]
Hi, thanks for your suggestion! I've had a look at it, shouldn't be too hard, the syntax looks fairly standard. Do you by chance know of a repositories that uses AS? I'd like to test it with some "real" files, most of the time is actually spent creating test source files to make sure everything works :wink:

**Comment by georgjz** [comment]
I just pushed an update, version 0.4.0 should now support The Macroassembler AS for 68k. The documentation for AS is a bit messy, could well be that I missed some pseudo functions/keywords/etc. If you find anything amiss, please feel free to open a new issue! Or comment here.

I'm still figuring out some of the macro commands that include [ and ], I'll make a separate issue #9 for that as reminder.

**Comment by flamewing** [comment]
Wow, that was quick. In any event, here is a repository that uses AS, and a lot of its features: [https://github.com/sonicretro/s2disasm](https://github.com/sonicretro/s2disasm)

It is a bit messy because most things are in a few large source files, but it should be fast enough in VSCode.

Anyway, thanks!

**Comment by georgjz** [comment]
No problem, I had spent the day fighting build systems, so I was happy to have something else to do that *does not* involve build systems (at least, not obviously).
